SET
  SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";

SET
  time_zone = "+00:00";

CREATE TABLE
  user (
    id INT(11) UNSIGNED NOT NULL,
    user_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
  );

CREATE TABLE
  project (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    `desc` TEXT NOT NULL,
    type ENUM("REALISATIONS", "PROJETS") NOT NULL,
    date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  );

CREATE TABLE
  image (
    id INT PRIMARY KEY AUTO_INCREMENT,
    imgLink VARCHAR(255) NOT NULL,
    alt TINYTEXT NOT NULL,
    date DATETIME DEFAULT CURRENT_TIMESTAMP,
    project_id INT NULL,
    CONSTRAINT fk_image_project FOREIGN KEY (project_id) REFERENCES project(id) ON DELETE CASCADE
  );

INSERT INTO
  user
VALUES
  ("Erwan, erwan.fillaud@gmail, Hooky2022!");